services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  celery_worker:
    build: .
    command: poetry run celery -A app.worker worker --loglevel=info --concurrency=4
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
    env_file:
      - .env